import type { ChecklistGroup } from "@/types/api";

export interface ChecklistItemRef {
  category: string;
  item: string;
  key: string;
}

export function flattenChecklist(template: ChecklistGroup[]): ChecklistItemRef[] {
  return template.flatMap((g) =>
    g.items.map((item) => ({ category: g.category, item, key: `${g.category}::${item}` })),
  );
}

/** The first N still-incomplete items, in template order — matches the "Still to do:
 *  1. Review travel insurance / 2. Prepare medical kit / 3. Review vaccine information"
 *  presentation from the product spec. */
export function stillToDo(
  template: ChecklistGroup[],
  checkedKeys: string[],
  limit = 3,
): ChecklistItemRef[] {
  const checked = new Set(checkedKeys);
  return flattenChecklist(template)
    .filter((ref) => !checked.has(ref.key))
    .slice(0, limit);
}

/**
 * Plain-text export a person can download and keep, print, or paste anywhere — doesn't
 * require a PDF library or a server round-trip for something this simple.
 */
export function buildChecklistText(params: {
  title: string;
  template: ChecklistGroup[];
  checkedKeys: string[];
}): string {
  const checked = new Set(params.checkedKeys);
  const total = flattenChecklist(params.template).length;
  const completed = params.checkedKeys.length;

  const lines: string[] = [params.title, `${completed} / ${total} complete`, ""];

  for (const group of params.template) {
    lines.push(group.category);
    for (const item of group.items) {
      const key = `${group.category}::${item}`;
      lines.push(`  [${checked.has(key) ? "x" : " "}] ${item}`);
    }
    lines.push("");
  }

  lines.push("Generated by Tropikit — tropikit app");
  return lines.join("\n");
}

export function downloadChecklistText(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
